# -*- coding: utf-8 -*-
"""randomGraphGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mmEVs0pKwR8qB0_w7jc6URHIwm-977SR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def plot_risk_of_outbreak(risk_of_outbreak):
    plt.figure(figsize=(8, 6))
    plt.plot(risk_of_outbreak, marker='o', color='r')
    plt.title('Risk of Outbreak')
    plt.xlabel('Days')
    plt.ylabel('Risk')
    plt.grid(True)
    plt.show()

def plot_cases(cases):
    plt.figure(figsize=(8, 6))
    plt.plot(cases, marker='o', color='g')
    plt.title('Cases')
    plt.xlabel('Days')
    plt.ylabel('Number of Cases')
    plt.grid(True)
    plt.show()

def plot_hospital_capacity(current_hospital_capacity):
    plt.figure(figsize=(8, 6))
    plt.plot(current_hospital_capacity, marker='o', color='b')
    plt.title('Current Hospital Capacity')
    plt.xlabel('Days')
    plt.ylabel('Capacity')
    plt.grid(True)
    plt.show()

def plot_current_risk(current_risk):
    plt.figure(figsize=(8, 6))
    plt.plot(current_risk, marker='o', color='m')
    plt.title('Current Risk')
    plt.xlabel('Days')
    plt.ylabel('Risk')
    plt.grid(True)
    plt.show()

def generate_random_data():
    # Generate random data for risk of outbreak, cases, current hospital capacity, and current risk
    num_days = 30
    risk_of_outbreak = np.random.randint(0, 100, size=num_days)
    cases = np.random.randint(0, 50, size=num_days)
    current_hospital_capacity = np.random.randint(50, 200, size=num_days)
    current_risk = np.random.rand(num_days) * 0.5 + 0.3  # Random values between 0.3 and 0.8 for current risk
    return risk_of_outbreak, cases, current_hospital_capacity, current_risk

# Generate random data
risk_of_outbreak, cases, current_hospital_capacity, current_risk = generate_random_data()

# Plot each variable using respective functions
plot_risk_of_outbreak(risk_of_outbreak)
plot_cases(cases)
plot_hospital_capacity(current_hospital_capacity)
plot_current_risk(current_risk)



